better update

diff --git a/.github/workflows/i18n-push-translations-poeditor.yml b/.github/workflows/i18n-push-translations-poeditor.yml
--- a/.github/workflows/i18n-push-translations-poeditor.yml
+++ b/.github/workflows/i18n-push-translations-poeditor.yml
@@ -35,24 +35,21 @@ jobs:
           echo "Uploading new terms from ${file}"
           # see POEditor Upload API: https://poeditor.com/docs/api#projects_upload
 
-          languages=("en" "fr" "it" "de")
-          for lang in "${languages[@]}"; do
-            echo "Uploading ${files[$lang]} for language $lang"
-            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
-              -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
-              -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
-              -F "language=$lang" \
-              -F "updating=terms_translations" \
-              -F "overwrite=1" \
-              -F "sync_terms=1" \
-              -F "file=@${file}")
+          echo "Uploading for referenc language 'en'"
+          response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
+            -F "api_token=${{ secrets.POEDITOR_API_TOKEN }}" \
+            -F "id=${{ secrets.POEDITOR_PROJECT_ID }}" \
+            -F "language=en" \
+            -F "updating=terms_translations" \
+            -F "read_from_source=1" \
+            -F "overwrite=1" \
+            -F "sync_terms=1" \
+            -F "fuzzy_trigger=1" \
+            -F "file=@${file}")
 
-            status=$(echo $response | jq -r '.response.status')
-            echo "API Response: $response"
-            if [ "$status" != "success" ]; then
-              echo "Error uploading file for $lang: $response"
-              exit 1
-            fi
-            echo "Waiting for 30 seconds to respect rate limits..."
-            sleep 30
-          done
+          status=$(echo $response | jq -r '.response.status')
+          echo "API Response: $response"
+          if [ "$status" != "success" ]; then
+            echo "Error uploading file for $lang: $response"
+            exit 1
+          fi
